models/Category.php
<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 08.02.18
 * Time: 15:29
 */

namespace app\models;
use yii\db\ActiveRecord;


class Category extends ActiveRecord
{
    public static function tableName(){
        return 'categories';
    }

    public function getProducts(){
        return $this->hasMany(Product::className(), ['parent' => 'id']);
    }
}

controllers/PostController.php
<?php
namespace app\controllers;
use app\models\Category;
use Yii;
use app\models\TestForm;

class PostController extends AppController{
  public $layout = 'basic';

  public function beforeAction($action){
    if($action->id == 'index'){
      $this->enableCsrfValidation = false;
    }
    return parent::beforeAction($action);
  }

  public function actionIndex(){
    if(Yii::$app->request->isAjax){
      debug(Yii::$app->request->post());
      return 'test';
    }

    $model = new TestForm();

    if($model->load(Yii::$app->request->post())){
        if($model->validate()){
            Yii::$app->session->setFlash('success', 'Данные приняты');
            return $this->refresh();
        } else {
            Yii::$app->session->setFlash('error', 'Ошибка');
        }
    }
    return $this->render('test', compact('model'));
  }

  public function actionShow(){
        $this->view->title = 'Одна статья';
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'Ключевики...']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'Описание страници']);

        //$cats = Category::find()->all();
      //$cats = Category::find()->orderBy(['id' => SORT_DESC])->all();
      //$cats = Category::find()->asArray()->all();
      //$cats = Category::find()->where('parent=691')->all();
      //$cats = Category::find()->where(['parent' => 691])->all();
      //$cats = Category::find()->asArray()->where(['like', 'title', 'pp'])->all();
      //$cats = Category::find()->asArray()->where(['<=', 'id', 695])->all();
      //$cats = Category::find()->where('parent=691')->limit(1)->all();
      //$cats = Category::find()->asArray()->limit(1)->where('parent=691')->one();
      //$cats = Category::find()->asArray()->limit(1)->where('parent=691')->count();
      //$cats = Category::findOne(['parent' => 691]);
      //$cats = Category::findAll(['parent' => 691]);
      //$query = "SELECT * FROM categories WHERE title LIKE '%pp%'";
      //$cats = Category::findBySql($query)->all();
      //$query = "SELECT * FROM categories WHERE title LIKE :search";
      //$cats = Category::findBySql($query, ['search' => '%pp%'])->all();
      $cats = Category::findOne(694);
        return $this->render('show', compact('cats'));
  }
}

views/post/show.php
<?php $this->beginBlock('block1'); ?>
<h1>Заголовок страницы</h1>
<?php $this->endBlock(); ?>

<h1>Show Action</h1>
<button id="btn" class="btn btn-success">Click me...</button>

<?php debug($cats); ?>
<?= count($cats->products) ?>
<?php debug($cats); ?>
<?php
//$this->registerJsFile('@web/js/scripts.js', ['depends' => 'yii\web\YiiAsset']);
?>
<?php
//$this->registerJS("$('.container').append('<p>SHOW!!!</p>');", \yii\web\View::POS_LOAD);
//$this->registerCss('.container{background: #ccc;}');
?>

<?php

$js = <<<JS
  $('#btn').on('click', function(){
    $.ajax({
      url: 'index.php?r=post/index',
      data: {test: '123'},
      type: 'POST',
      success: function(res){
        console.log(res);
      },
      error: function(){
        alert('Error!');
      }
    });
  });
JS;

$this->registerJS($js);

?>

views/post/test.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>

<h1>Test Action</h1>
<?php
//debug($model);
 ?>
<?php if(Yii::$app->session->hasFlash('success')) : ?>
    <div class="alert alert-success alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <?= Yii::$app->session->getFlash('success') ?>
    </div>
<?php endif; ?>

<?php if(Yii::$app->session->hasFlash('error')) : ?>
    <div class="alert alert-danger alert-dismissable">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <?= Yii::$app->session->getFlash('error') ?>
    </div>
<?php endif; ?>

<?php $form = ActiveForm::begin(['options' => ['id' => 'testForm']]); ?>
<?= $form->field($model, 'name')->label('Имя') ?>
<?= $form->field($model, 'email')->input('email') ?>
<?= $form->field($model, 'text')->label('Текст сообщения')->textarea(['rows' => 5]) ?>
<?= Html::submitButton('Отправить', ['class' => 'btn btn-success']); ?>
<?php ActiveForm::end(); ?>