controllers/PostController.php
<?php
namespace app\controllers;
use app\models\Category;
use Yii;
use app\models\TestForm;

class PostController extends AppController{
  public $layout = 'basic';

  public function beforeAction($action){
    if($action->id == 'index'){
      $this->enableCsrfValidation = false;
    }
    return parent::beforeAction($action);
  }

  public function actionIndex(){
    if(Yii::$app->request->isAjax){
      debug(Yii::$app->request->post());
      return 'test';
    }

    $model = new TestForm();

    if($model->load(Yii::$app->request->post())){
        if($model->validate()){
            Yii::$app->session->setFlash('success', 'Данные приняты');
            return $this->refresh();
        } else {
            Yii::$app->session->setFlash('error', 'Ошибка');
        }
    }
    return $this->render('test', compact('model'));
  }

  public function actionShow(){
        $this->view->title = 'Одна статья';
        $this->view->registerMetaTag(['name' => 'keywords', 'content' => 'Ключевики...']);
        $this->view->registerMetaTag(['name' => 'description', 'content' => 'Описание страници']);

        //$cats = Category::find()->all();
      //$cats = Category::find()->orderBy(['id' => SORT_DESC])->all();
      //$cats = Category::find()->asArray()->all();
      //$cats = Category::find()->where('parent=691')->all();
      //$cats = Category::find()->where(['parent' => 691])->all();
      //$cats = Category::find()->asArray()->where(['like', 'title', 'pp'])->all();
      //$cats = Category::find()->asArray()->where(['<=', 'id', 695])->all();
      //$cats = Category::find()->where('parent=691')->limit(1)->all();
      //$cats = Category::find()->asArray()->limit(1)->where('parent=691')->one();
      //$cats = Category::find()->asArray()->limit(1)->where('parent=691')->count();
      //$cats = Category::findOne(['parent' => 691]);
      //$cats = Category::findAll(['parent' => 691]);
      //$query = "SELECT * FROM categories WHERE title LIKE '%pp%'";
      //$cats = Category::findBySql($query)->all();
      //$query = "SELECT * FROM categories WHERE title LIKE :search";
      //$cats = Category::findBySql($query, ['search' => '%pp%'])->all();
      $cats = Category::findOne(694);
        return $this->render('show', compact('cats'));
  }
}

views/layouts/basic.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

//use app\widgets\Alert;
use yii\helpers\Html;
//use yii\bootstrap\Nav;
//use yii\bootstrap\NavBar;
//use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?= Html::csrfMetaTags() ?>
  <title><?= Html::encode($this->title) ?></title>
  <?php $this->head() ?>
</head>
<body>
  <?php $this->beginBody() ?>
  <div class="wrap">
    <div class="container">

      <ul class="nav nav-pills">
        <li role="presentation" class="active"><?= Html::a('Главная', ['site/index']) ?></li>
        <li role="presentation"><?= Html::a('Статьи', ['post/index']) ?></li>
        <li role="presentation"><?= Html::a('Статья', ['post/show']) ?></li>
      </ul>

        <?php if(isset($this->blocks['block1'])) : ?>
            <?php echo $this->blocks['block1']; ?>
        <?php endif; ?>

      <?= $content ?>
    </div>
  </div>

  <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index']],
            ['label' => 'Articles', 'url' => ['/post/index']],
            ['label' => 'About', 'url' => ['/site/about']],
            ['label' => 'Contact', 'url' => ['/site/contact']],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>